### ISSUE TITLE
Duplicate Member Name

### ISSUE THREAD

**Issue by kylepauljohnson** [kenakamu/UCWA2.0-CS#13]
I was working with the library and ran into an issue while trying to initialize it to where it would throw the following exception. 

A member with the name 'batch' already exists on 'Microsoft.Skype.UCWA.Models.Application+InternalLinks'. Use the JsonPropertyAttribute to specify another name.

**Stack trace:** 
   at Microsoft.Skype.UCWA.UCWAClient.<CreateApplication>d__444.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Skype.UCWA.UCWAClient.<Initialize>d__420.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

**Comment by kylepauljohnson** [comment]
After looking into this further it appears that its throwing the exception when it's trying to desalinize the response.  For now I corrected the behavior by commenting out the Batch property inside of Internal Links, and renaming public property Events to InternalEvents.  This seems to at least fix what I need.

**Comment by kenakamu** [comment]
So the response format is not matching then... It is possible for you to provide me the response data (of course you can remove sensible data)

**Comment by kenakamu** [comment]
I couldn't repro the issue so far. so please share your incoming json

**Comment by kylepauljohnson** [comment]
Feel free to close the issue.  I have had to abandon this project and won't have time to return to it anytime soon.
