### ISSUE TITLE
SFB Connector is going offline

### ISSUE THREAD

**Issue by RajaniJillaGit** [kenakamu/UCWA2.0-CS#59]
Hi Team,

We have downloaded the connector and have hosted this scheduler which always keeps the user online on Azure web job. However, we are observing the user is going offline often and only after restart of web job, user is coming online. After enabling logs, below are the details that are captured and are not helping to dig in to the issue.

![image](https://user-images.githubusercontent.com/37394330/45213770-1de2e080-b2b6-11e8-8528-df0157920d8e.png)
![image](https://user-images.githubusercontent.com/37394330/45213794-38b55500-b2b6-11e8-8916-7314ecb4ca15.png)

Would be helpful if you can provide any insight on this.

**Comment by baywet** [comment]
Hi @RajaniJillaGit 
This error doesn't provide a lot of information. Any chance you could provide a bigger stack trace?

**Comment by dipincluster** [comment]
@baywet  @kenakamu 
Getting the Same Issue , and this is the Stack Trace 

System.NullReferenceException: Object reference not set to an instance of an object.     at Microsoft.Skype.UCWA.UCWAClient.<Initialize>d__421.MoveNext() in D:\UnileverUnabot\SFB\MultiPoolSFBConnector-Final\SFBConnector\UCWASDK\UCWAClient.cs:line 646


   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)     at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)     at System.Threading.Tasks.Task.Wait()     at SFBConnector.CustomConnector.Signin(String username, String password) in D:\UnileverUnabot\SFB\MultiPoolSFBConnector-Final\SFBConnector\TestClient\CustomConnector.cs:line 394
